// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ateszuxiuonjnxmwvvok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0ZXN6dXhpdW9uam54bXd2dm9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNTk2MzIsImV4cCI6MjA2NjYzNTYzMn0.8qlIjLu6I0-rHYVjzlV-jJjcErkMjVVlRMzDiaGF3og";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);